ALTER TABLE "Collection"
  ADD COLUMN IF NOT EXISTS "tippingFeeCollected" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "gstCollected" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "paymentDate" TIMESTAMP(3);
