ALTER TABLE "LoginActivity" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "LoginActivity" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
ALTER TABLE "LoginActivity" ADD COLUMN IF NOT EXISTS "locationLabel" TEXT;
