import { useEffect, useState } from 'react';
import client from '../../api/client';
import Layout from '../../components/layout/Layout';

export default function ReceiptDownloadsPage() {
  const [collections, setCollections] = useState([]);
  const [message, setMessage] = useState('');

  useEffect(() => {
    const loadReceipts = async () => {
      try {
        const response = await client.get('/collections/my');
        setCollections(response.data || []);
      } catch (_error) {
        setMessage('Unable to load receipts.');
      }
    };

    loadReceipts();
  }, []);

  return (
    <Layout title="Receipt Downloads">
      <section className="max-w-2xl rounded-xl bg-white p-6 shadow-sm">
        <p className="text-gray-700">Download receipts generated by admin payment verification.</p>
        {message && <p className="mt-3 text-sm text-gray-700">{message}</p>}
        <div className="mt-4 flex flex-col gap-2">
          {collections.filter((item) => item.receipt?.receiptNumber && item.paid).map((item) => (
            <a
              key={item.id}
              href={`${client.defaults.baseURL?.replace('/api/v1', '')}/api/v1/collections/${item.id}/receipt-download`}
              target="_blank"
              rel="noreferrer"
              className="inline-flex w-fit rounded-md bg-primaryGreen px-3 py-2 text-sm text-white"
            >
              Download {item.month}/{item.year} receipt
            </a>
          ))}
          {!collections.filter((item) => item.receipt?.receiptNumber && item.paid).length && (
            <p className="text-sm text-gray-600">No receipts available yet.</p>
          )}
        </div>
      </section>
    </Layout>
  );
}
