ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "userPin" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pinAttempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pinCreatedAt" TIMESTAMP(3);
